# Generated by Django 4.0.6 on 2025-06-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tests',
        ),
    ]
